cookie:
  expiry_days: 30
  key: some_signature_key # Must be a string
  name: some_cookie_name
credentials:
  usernames:
    ai-shifu:
      email: support@ai-shifu.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: ai-shifu
      password: $2b$12$rDZH4G5IrAqm7NETcny/TO.QNNmT0dUi3B2rV43PFHDxRWuHfc/Ki # Will be hashed automatically
      roles:
      - admin
oauth2:
  google: # Follow instructions: https://developers.google.com/identity/protocols/oauth2
    client_id: # To be filled
    client_secret: # To be filled
    redirect_uri: # URL to redirect to after OAuth2 authentication
  microsoft: # Follow instructions: https://learn.microsoft.com/en-us/graph/auth-register-app-v2
    client_id: # To be filled
    client_secret: # To be filled
    redirect_uri: # URL to redirect to after OAuth2 authentication
    tenant_id: # To be filled
pre-authorized:
  emails:
  - melsby@gmail.com
