services:
  ai-shifu-api:
    container_name: ai-shifu-api
    image: aishifu/ai-shifu-api:latest
    entrypoint: ["sh", "-c", "flask db upgrade && exec gunicorn -w 4 -b 0.0.0.0:5800 'app:app' --timeout 300 --log-level debug --access-logfile /var/log/app.log --capture-output"]
    env_file:
      - ./.env
    environment:
      - MODE=api
    depends_on:
      - ai-shifu-mysql
      - ai-shifu-redis
  ai-shifu-web:
    container_name:  ai-shifu-web
    image: aishifu/ai-shifu-web:latest
    env_file:
      - ./.env
    depends_on:
      - ai-shifu-api
  ai-shifu-nginx:
    container_name: ai-shifu-nginx
    image: nginx:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ai-shifu-web
      - ai-shifu-api
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  ai-shifu-mysql:
    container_name: ai-shifu-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ai-shifu
      - MYSQL_DATABASE=ai-shifu
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
  ai-shifu-redis:
    container_name: ai-shifu-redis
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=ai-shifu
      - REDIS_USER=root
    volumes:
      - ./redis_data:/data

# en
