services:
  ai-shifu-api:
    container_name: ai-shifu-api
    # Production uses specific version tags for stability
    # Update this manually to the desired release version
    # Available versions: https://github.com/ai-shifu/ai-shifu/releases
    image: aishifu/ai-shifu-api:v0.7.3
    entrypoint: ["sh", "-c", "until timeout 1 bash -c 'cat < /dev/null > /dev/tcp/ai-shifu-mysql/3306'; do sleep 1; done && flask db upgrade && exec gunicorn -w 4 -b 0.0.0.0:5800 'app:app' --timeout 300 --log-level info --access-logfile /var/log/app.log --capture-output"]
    env_file:
      - ./.env
    depends_on:
      - ai-shifu-mysql
      - ai-shifu-redis
    restart: unless-stopped

  ai-shifu-web:
    container_name:  ai-shifu-web
    image: aishifu/ai-shifu-web:v0.7.3
    env_file:
      - ./.env
    depends_on:
      - ai-shifu-api
    restart: unless-stopped

  ai-shifu-cook-web:
    container_name: ai-shifu-cook-web
    image: aishifu/ai-shifu-cook-web:v0.7.3
    env_file:
      - ./.env
    depends_on:
      - ai-shifu-api
    restart: unless-stopped

  ai-shifu-nginx:
    container_name: ai-shifu-nginx
    image: nginx:stable
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ai-shifu-web
      - ai-shifu-api
      - ai-shifu-cook-web
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  ai-shifu-mysql:
    container_name: ai-shifu-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  ai-shifu-redis:
    container_name: ai-shifu-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - ./redis_data:/data
