services:
  ai-shifu-api-dev:
    container_name: ai-shifu-api-dev
    image: ai-shifu-api-dev:latest
    command: ["sh", "-c", "until timeout 1 bash -c 'cat < /dev/null > /dev/tcp/ai-shifu-mysql/3306'; do sleep 1; done && flask db upgrade && cd /app && exec flask run --reload --debugger --host=0.0.0.0 --port=5800"]
    env_file:
      - ./.env
    volumes:
      - ../src/api/:/app/
    depends_on:
      - ai-shifu-mysql
      - ai-shifu-redis
  ai-shifu-web-dev:
    container_name:  ai-shifu-web-dev
    image: ai-shifu-web-dev:latest
    command: ["sh", "-c", "npm run start:dev"]
    depends_on:
      - ai-shifu-api-dev
    env_file:
      - ./.env
    volumes:
      - ../src/web/:/app/
  ai-shifu-cook-dev:
    container_name: ai-shifu-cook-dev
    image: ai-shifu-cook-dev:latest
    volumes:
      - ./cook_data:/data
    env_file:
      - ./.env
    depends_on:
      - ai-shifu-mysql
  ai-shifu-nginx-dev-dev:
    container_name: ai-shifu-nginx-dev
    image: nginx:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ai-shifu-web-dev
      - ai-shifu-api-dev
    restart: always
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf

  ai-shifu-mysql:
    container_name: ai-shifu-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ai-shifu
      MYSQL_DATABASE: ai-shifu
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  ai-shifu-redis:
    container_name: ai-shifu-redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
